Solution/RestaurantBookingSystem/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantBookingSystem.Infrastructure.Providers;
using RestaurantBookingSystem.Infrastructure.Repositories;
using RestaurantBookingSystem.Infrastructure;
using RestaurantBookingSystem.Helpers;

namespace RestaurantBookingSystem.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        // Initialize A custom cookie based temp data provider for the controller
        protected override ITempDataProvider CreateTempDataProvider()
        {
            return new CookieBasedTempDataProvider();
        }

        //
        // GET: /Customers/

        public ActionResult Index()
        {
            return null;
        }

        //
        // GET: /Customers/CheckIn

        public ActionResult CheckIn()
        {
            return null;
        }

        //
        // GET: /Customers/CheckIn
        [HttpPost]
        public ActionResult CheckIn(int bookingid)
        {
            return null;
        }
    }
}

Solution/RestaurantBookingSystem/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using RestaurantBookingSystem.Helpers;
using System.Web.Mvc;

namespace RestaurantBookingSystem.Controllers
{
    public class ImagesController : Controller
    {
        [OutputCache(Duration = 3600, VaryByHeader = "Etag")]
        public FileStreamResult GetImage(string id)
        {
            Guid guid;
            if (Guid.TryParse(id,out guid) && guid != Guid.Empty)
            {
                using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
                using (var cmd = new SqlCommand("[dbo].[GetBlob]", cn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;

                    try
                    {
                        cn.Open();
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.SequentialAccess))
                        {
                            if (rdr.HasRows && rdr.Read())
                            {
                                var result = new
                                                 {
                                                     ID = rdr.TryGetDataAsGuid(0),
                                                     MimeType = rdr.TryGetDataAsString(1),
                                                     ImageBlobStream = rdr.GetSqlBytes(2).Stream,
                                                     Sha1Hash = rdr.GetString(3)
                                                 };
                                if (Response != null)
                                    Response.Cache.SetETag(result.Sha1Hash);
                                return File(result.ImageBlobStream, result.MimeType);
                            }
                        }
                    }
                    catch (SqlException)
                    {
                        return null;
                    }
                }
            }
            //Set etag even for invalid image response so that they dont come back again asking for it
            Response.Cache.SetETag(CryptographyHelper.GetSHA1Hash(guid.ToString("n")));
            return null;
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Put)]
        [Authorize]
        public Guid PutImage(HttpPostedFileBase image, Guid? id)
        {
            var result = Guid.Empty;
            if (image == null || image.ContentLength < 1)
                return result;
            
            using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
            using (var cmd = new SqlCommand("[dbo].[AddBlob]", cn))
            {
                var guid = id ?? Guid.NewGuid();
                var buffer = image.InputStream.ReadToEnd();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;
                cmd.Parameters.Add("@MIMETYPE", SqlDbType.Char, 20).Value = image.ContentType;
                cmd.Parameters.Add("@BLOB", SqlDbType.VarBinary, image.ContentLength).Value = buffer;
                cmd.Parameters.Add("@SHA1HASH", SqlDbType.Char, 40).Value =
                    CryptographyHelper.GetSHA1Hash(buffer);

                try
                {
                    cn.Open();
                    return Guid.TryParse(cmd.ExecuteScalar().ToString(), out result) ? result : Guid.Empty;
                }
                catch (SqlException)
                {
                    return result;
                }
                
            }
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Delete)]
        [Authorize(Roles = "Admin, Employee")]
        [OutputCache(Duration = 3600, VaryByParam = "id")]
        public bool DeleteImage(string id)
        {
            var result = false;
            Guid guid;
            if (id == null || !Guid.TryParse(id, out guid) || guid == Guid.Empty)
                return false;

            using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
            using (var cmd = new SqlCommand("[dbo].[DeleteBlob]", cn))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;

                try
                {
                    cn.Open();
                    return result = cmd.ExecuteNonQuery() == 1;
                }
                catch (SqlException)
                {
                    return result;
                }
            }
        }
    }
}

Solution/RestaurantBookingSystem/Controllers/MenuController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantBookingSystem.Infrastructure.DataEntities;
using RestaurantBookingSystem.Infrastructure.Providers;
using RestaurantBookingSystem.Infrastructure.Repositories;
using RestaurantBookingSystem.Infrastructure;
using RestaurantBookingSystem.Helpers;
using RestaurantBookingSystem.Models;

namespace RestaurantBookingSystem.Controllers
{
    [Authorize(Roles = "Admin, Employee")]
    public class MenuController : Controller
    {
        private readonly RestaurantMenuItemRepository Repository;
        private readonly int PageSize = AppConfigHelper.MediumPageSize;

        // Initialize A custom cookie based temp data provider for the controller
        protected override ITempDataProvider CreateTempDataProvider()
        {
            return new CookieBasedTempDataProvider();
        }

        //
        // GET: /Menu/

        public ActionResult Index(int? id, int? page)
        {
            var allmenu = Repository.SelectAll();
            if (id.HasValue && id > 1)
                allmenu = allmenu.Where(offer => offer.ItemId == id);
            var paginatedlist = new PaginatedList<RestaurantMenuItem>(allmenu, page ?? 1, page.HasValue ? PageSize : allmenu.Count());
            return View(paginatedlist);
        }

        //
        // GET: /Menu/Today
        [Authorize(Roles = "Employee")]
        public ActionResult Today()
        {
            ViewBag.Title = ViewBag.Title ?? "Today's Servings";
            return ServingsOn(DateTime.UtcNow.Date);
        }

        //
        // GET: /Menu/ServingsOn
        [Authorize(Roles = "Employee")]
        public ActionResult ServingsOn()
        {
            ViewBag.Title = ViewBag.Title ?? "Servings On";
            return Today();
        }

        //
        // POST: /Menu/ServingsOn
        [HttpPost]
        [Authorize(Roles = "Employee")]
        public ActionResult ServingsOn(DateTime fordate)
        {
            //reduce the date precision to Date only by omiting the time part
            fordate = fordate.Floor(DateTimeHelper.DateTimePrecisionLevel.Days);
            var result = Repository.SelectBookedMenuItems(fordate);
            if (Request.IsAjaxRequest())
            {
                //If request is Ajax then send a JSON representation of the Dictionary, Also send the Date as a string so it can be easily parsed by client
                return
                    Json(
                        result
                        .ToDictionary(item => fordate.ToISODateTimeString(), item => result)
                        .ToLookup(kvp => new { kvp.Key, kvp.Value }));
            }
            return View("ServingsOn", result);
        }
        
        //
        // GET: /Menu/Add

        public ActionResult Add()
        {
            return View(new RestaurantMenuViewModel());
        } 

        //
        // POST: /Menu/Add

        [HttpPost]
        public ActionResult Add(RestaurantMenuViewModel model, HttpPostedFileBase menuimage)
        {
            try
            {
                //Explicitly Validate Model for menu image
                if (menuimage == null || menuimage.ContentLength < 1 || (menuimage.ContentType != "image/jpeg" && menuimage.ContentType != "image/png"))
                    ModelState.AddModelError("addstatus", "A Menu Item needs to have a valid Image, Only JPEG and PNG images are supported");
                if (ModelState.IsValid)
                {
                    // Attempt to add the offer
                    var restauranttable = new RestaurantMenuItem
                    {
                        Name = model.Name,
                        Description = model.Description,
                        Price = model.Price,
                        PictureFile = new ImagesController().PutImage(menuimage, null).ToString("n")
                    };

                    var itemid = Repository.Add(restauranttable);
                    if (itemid > 0)
                    {
                        TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                        {
                            Message = String.Format("Menu Item \"{0}\" with Id:{1} was successfully Added", model.Name, itemid),
                            Result = true,
                            State = ActionResultNotification.MessageState.Information
                        };
                        return RedirectToAction("Index");
                    }
                }
                // If we got this far, something failed, redisplay form
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = ModelState.ContainsKey("addstatus") ? ModelState["addstatus"].Errors[0].ErrorMessage : "There was an Error in adding the new Menu item, please try again",
                    Result = false,
                    State = ActionResultNotification.MessageState.Warning
                };
                return View(model);
            }
            catch (Exception e)
            {
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = e.Message,
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
        }
        
        //
        // GET: /Menu/Edit/5
 
        public ActionResult Edit(int id)
        {
            var menuitem = Repository.Find(id);

            if (menuitem != null)
            {
                return View(new RestaurantMenuViewModel(menuitem));
            }
            TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
            {
                Message = String.Format("No such Menu item Exists !"),
                Result = false,
                State = ActionResultNotification.MessageState.Error
            };
            return RedirectToAction("Index");
        }

        //
        // POST: /Menu/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, RestaurantMenuViewModel model, HttpPostedFileBase menuimage)
        {
            try
            {
                // Get previous details
                var existingmenuitem = Repository.Find(id);
                if (existingmenuitem == null) throw new InvalidOperationException("Sorry the update cannot be done as no such menu Item exist");

                if (menuimage != null && (menuimage.ContentLength < 1
                    || (menuimage.ContentType != "image/jpeg" && menuimage.ContentType != "image/png")))
                {
                    ModelState.AddModelError("updatestatus",
                                             "A Menu Item needs to have a valid Image, Only JPEG and PNG images are supported");
                    model.PictureFileName = existingmenuitem.PictureFile;
                }

                if (ModelState.IsValid)
                {

                    // Attempt to Update the offer
                    if (menuimage != null && menuimage.ContentLength > 0)
                    {
                        var previd = existingmenuitem.PictureFile;
                        var imagecontroller = new ImagesController();
                        existingmenuitem.PictureFile =
                            imagecontroller.PutImage(menuimage, null).ToString("n");
                        // if both image ids are not same then delete the prev id.
                        if (!String.Equals(previd, existingmenuitem.PictureFile)) imagecontroller.DeleteImage(previd);
                    }

                    existingmenuitem.Description = model.Description;
                    existingmenuitem.Name = model.Name;
                    existingmenuitem.Price = model.Price;

                    //And push the changed details
                    if (Repository.Update(existingmenuitem))
                    {
                        TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                        {
                            Message = String.Format("Details for {0} was successfully Updated", existingmenuitem.Name),
                            Result = true,
                            State = ActionResultNotification.MessageState.Information
                        };
                        return RedirectToAction("Index");
                    }
                }
                // If we got this far, something failed, redisplay form
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = ModelState.ContainsKey("updatestatus") ? ModelState["updatestatus"].Errors[0].ErrorMessage : "Cannot Update the details of the offer with given details, please try again",
                    Result = false,
                    State = ActionResultNotification.MessageState.Warning
                };
                return View(model);
            }
            catch (Exception e)
            {
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = e.Message,
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
        }

        //
        // POST: /Menu/Delete/5

        //Only Ajax Request is processed, a normal post request is redirected to Index action method
        [HttpPost]

Solution/RestaurantBookingSystem/Views/Shared/ApplicationMenu.cshtml
@using RestaurantBookingSystem.Helpers
@using RestaurantBookingSystem.Infrastructure.DataEntities
@using RestaurantBookingSystem.Models
@{
    var pathcontroller = ViewContext.RouteData.GetRequiredString("controller");
    var pathaction = ViewContext.RouteData.GetRequiredString("action");
    Func<string, bool> isSelected = (c) => !c.IsNullOrEmpty() && String.Equals(c.ToUpperInvariant(), Url.Action(pathaction, pathcontroller).ToUpperInvariant());
    Func<string, string, List<NavigationMenuModel>, NavigationMenuModel> makeMenu =
        (name, actionurl, innermenu) => new NavigationMenuModel
                                        {
                                            Name = name,
                                            Link = actionurl,
                                            InnerMenu = innermenu,
                                            Selected = isSelected(actionurl) || (innermenu != null && innermenu.Any( inner => inner.Selected))
                                        };
    Func<UserBase.RestaurantUserRole, bool> useris = (role) => Request.IsAuthenticated && User.IsInRole(role.ToString());

    var mainmenu = new List<NavigationMenuModel>();

    mainmenu.Add(makeMenu("Home", Url.Action("Index", "Home"), null));

    if (!useris(UserBase.RestaurantUserRole.Admin))
    {
        var bookingmenu = new List<NavigationMenuModel>();

        bookingmenu.Add(makeMenu("New Booking", Url.Action("New", "Bookings"), null));
        if (useris(UserBase.RestaurantUserRole.Employee))
        {
            bookingmenu.Add(makeMenu("Todays Bookings", Url.Action("Today", "Bookings"), null));
        }
        if (useris(UserBase.RestaurantUserRole.Employee) || useris(UserBase.RestaurantUserRole.Customer) || useris(UserBase.RestaurantUserRole.Guest))
        {
            bookingmenu.Add(makeMenu("All Bookings", Url.Action("Index", "Bookings"), null));
            bookingmenu.Add(makeMenu("Find Booking", Url.Action("List", "Bookings"), null));
        }
        mainmenu.Add(Request.IsAuthenticated ? makeMenu("Booking", Url.Action("Index", "Bookings"), bookingmenu) : makeMenu("New Booking", Url.Action("New", "Bookings"), null));
    }

    if (useris(UserBase.RestaurantUserRole.Employee) || useris(UserBase.RestaurantUserRole.Admin))
    {
        var tablesmenu = new List<NavigationMenuModel>();
        {
            tablesmenu.Add(makeMenu("Current Status", Url.Action("CurrentStatus", "Tables"), null));
            tablesmenu.Add(makeMenu("Status On", Url.Action("StatusOn", "Tables"), null));
        }
        if (useris(UserBase.RestaurantUserRole.Admin))
        {
            tablesmenu.Add(makeMenu("List All", Url.Action("Index", "Tables"), null));
            tablesmenu.Add(makeMenu("Add New", Url.Action("Add", "Tables"), null));
        }
        mainmenu.Add(makeMenu("Tables", Url.Action("CurrentStatus", "Tables"), tablesmenu));
    }

    if (useris(UserBase.RestaurantUserRole.Employee) || useris(UserBase.RestaurantUserRole.Admin))
    {
        var menuitemsmenu = new List<NavigationMenuModel>();

        if (useris(UserBase.RestaurantUserRole.Employee))
        {
            menuitemsmenu.Add(makeMenu("Todays Servings", Url.Action("Today", "Menu"), null));
            menuitemsmenu.Add(makeMenu("Servings On", Url.Action("ServingsOn", "Menu"), null));
        }
        menuitemsmenu.Add(makeMenu("List All", Url.Action("Index", "Menu"), null));
        menuitemsmenu.Add(makeMenu("Add Menu Item", Url.Action("Add", "Menu"), null));
        mainmenu.Add(makeMenu("Menu", Url.Action("Index", "Menu"), menuitemsmenu));
    }

    //if (useris(UserBase.RestaurantUserRole.Employee))
    //{
    //    var customersmenu = new List<NavigationMenuModel>
    //        {
    //            makeMenu("Check In", Url.Action("CheckIn", "Customers"), null), 
    //            makeMenu("List Customers", Url.Action("Index", "Customers"), null)
    //        };

    //    mainmenu.Add(makeMenu("Customers", Url.Action("Index", "Customers"), customersmenu));
    //}

    if (useris(UserBase.RestaurantUserRole.Employee) || useris(UserBase.RestaurantUserRole.Admin))
    {
        var offermenu = new List<NavigationMenuModel>();

        offermenu.Add(makeMenu("List All", Url.Action("Index", "Offers"), null));
        if (useris(UserBase.RestaurantUserRole.Admin))
        {
            offermenu.Add(makeMenu("Add Offer", Url.Action("Add", "Offers"), null));
        }
        mainmenu.Add(makeMenu("Offers", Url.Action("Index", "Offers"), offermenu));
    }

    if (useris(UserBase.RestaurantUserRole.Admin))
    {
        var employeemenu = new List<NavigationMenuModel>();

        employeemenu.Add(makeMenu("List All", Url.Action("Index", "Employee"), null));
        employeemenu.Add(makeMenu("Add Employee", Url.Action("Add", "Employee"), null)); ;
        mainmenu.Add(makeMenu("Employees", Url.Action("Index", "Employee"), employeemenu));
    }

    if (Request.IsAuthenticated)
    {
        var accountmenu = new List<NavigationMenuModel>();
        if (useris(UserBase.RestaurantUserRole.Guest))
        {
            accountmenu.Add(makeMenu("Forget Me", Url.Action("LogOut", "Account"), null));
        }
        else
        {
            accountmenu.Add(makeMenu("Sign Out", Url.Action("LogOut", "Account"), null));
            accountmenu.Add(makeMenu("Profile", Url.Action("Index", "Account"), null));
            accountmenu.Add(makeMenu("Change Password", Url.Action("ChangePassword", "Account"), null));
        }

        mainmenu.Add(makeMenu("Account", !useris(UserBase.RestaurantUserRole.Guest) ? Url.Action("Index", "Account") : null, accountmenu));
    }

    if (!useris(UserBase.RestaurantUserRole.Employee))
    {
        mainmenu.Add(makeMenu("About", Url.Action("About", "Home"), null));
    }
}
<div class="menu-container">
    <ul>
        @*This foreach only goes 1 level deep, will think of some way to get recursion an go n level deep*@
        @foreach (var item in mainmenu)
        {
            if (item.InnerMenu == null)
            {
            <li><a href="@item.Link" class="@(item.Selected ? "a-menu-selected" : string.Empty)">@item.Name</a></li>
            }
            else
            {
            <li><a href="@item.Link" class="@(item.Selected ? "a-menu-selected" : string.Empty)">@item.Name</a>
                <ul class="ul-sub-menu @(useris(UserBase.RestaurantUserRole.Employee) && item.Link.Contains("Account") ? "ul-sub-menu-last" : "")">
                    @foreach (var inneritem in item.InnerMenu)
                    {
                        <li><a href="@inneritem.Link" class="@(inneritem.Selected ? "a-sub-menu-selected" : string.Empty)">@inneritem.Name</a></li>
                    }
                </ul>
            </li>
            }
        }
    </ul>
</div>

Solution/RestaurantBookingSystem/Views/Shared/UserLoginStatus.cshtml
@using RestaurantBookingSystem.Helpers
@using RestaurantBookingSystem.Infrastructure
@if (Uri.Compare(Request.Url, new Uri(Url.AbsoluteAction("Login", "Account", null)), UriComponents.Path, UriFormat.SafeUnescaped, StringComparison.OrdinalIgnoreCase) == 0){return;}
<div class="user-loginstatus ui-corner-all ui-widget-content">
    @if (Request.IsAuthenticated && User.Identity is RestaurantUserIdentity)
    {
        var identity = (RestaurantUserIdentity)User.Identity;
        <span class="user-loginstatus-text">Hello, @identity.FriendlyName
            @if (identity.GetAuthenticationType != FormsAuthenticationHelper.AuthenticationType.Guest)
            { 
                <text>|</text> @Html.ActionLink("[ Sign Out ]", "LogOut", "Account") 
            }
        </span>
    }
    else
    {
        <span class="user-loginstatus-text">@Html.ActionLink("[ Sign In ]", "LogIn", new { controller = "Account", returnurl = Request.RawUrl })</span>
    }
</div>

Solution/RestaurantBookingSystem/Views/Shared/ViewNotification.cshtml
@using RestaurantBookingSystem.Helpers
@using RestaurantBookingSystem.Infrastructure
@model ActionResultNotification
@{
    var state = Model.State == ActionResultNotification.MessageState.None ? "" : Model.State.ToString();
    var message = Model.State == ActionResultNotification.MessageState.None ? "" : Model.Message;
}
<div id="view_notification" style="display: none; position: fixed; width: 100%; z-index: 9999">
    <div class="ui-widget">
        <div id="view_notification_ui_state" class="@(Model.Result ? "ui-state-highlight" : "ui-state-error")" style="padding: 0 .7em;">
            <p>
                <span id="view_notification_icon" class="ui-icon @(Model.Result ? "ui-icon-info" : "ui-icon-alert")" style="float: left; margin-right: .3em;">
                </span><strong id="view_notification_state">@state: </strong><span id="view_notification_message">@message.</span></p>
        </div>
    </div>
</div>
<script type="text/javascript">
@if (Model.State != ActionResultNotification.MessageState.None)
{
    <text> $('#view_notification').slideDown(500).delay(3000).slideUp(1000); </text>
}
</script>

Solution/RestaurantBookingSystem/Views/Shared/tablestatus.cshtml
@using System.Drawing
@using RestaurantBookingSystem.Controllers
@using RestaurantBookingSystem.Infrastructure.DataEntities
@* ReSharper disable UnknownCssClass *@
@model IEnumerable<RestaurantTable>
@{
    if (Model.Count() < 1){ return;}
    var floorplanfile = Image.FromStream(new ImagesController().GetImage(Model.First().FloorPlanFileName).FileStream);
    var floorplanheight = floorplanfile.Height;
    var floorplanwidth = floorplanfile.Width;
    
}
<script type="text/javascript">
    TableStatusIMG = {
        Booked: '@Url.Content("~/Content/themes/base/images/blue.png")',
        Occupied: '@Url.Content("~/Content/themes/base/images/red.png")',
        Vacant: '@Url.Content("~/Content/themes/base/images/green.png")',
        BeingBooked : '@Url.Content("~/Content/themes/base/images/green_blue.png")'
    };
    window.bookingIsEnabled = false;
    (function () {
        $('#tabledetail').hide();
        $(document).ready(function () {
            $('.table-booking-status').hover(function (e) {
                var widgetheight = parseInt($('#tabledetail').css('height')) + parseInt($('#tabledetail').css('border-top-width')) + parseInt($('#tabledetail').css('border-bottom-width')) + parseInt($('#tabledetail').css('padding-top')) + parseInt($('#tabledetail').css('padding-bottom'));
                var widgetwidth = parseInt($('#tabledetail').css('width')) + parseInt($('#tabledetail').css('border-left-width')) + parseInt($('#tabledetail').css('border-right-width')) + parseInt($('#tabledetail').css('padding-left')) + parseInt($('#tabledetail').css('padding-right'));
                if (window.innerHeight < e.screenY + widgetheight)
                    dtop = dtop - (widgetheight - 20);
                if (window.innerWidth < e.screenX + widgetwidth + 20)
                    dleft = dleft - (widgetwidth + 40);
                tabledetail.status = $('#table_status' + tabledetail.tableid).attr('data-status');
                $('#tabledetail').stop(true, true);
                $('#tabledetail_table_id').text(tabledetail.tableid);
                $('#tabledetail_table_price').text(tabledetail.price);
                $('#tabledetail_table_status').text(tabledetail.status);
                $('#tabledetail_table_capacity').text(tabledetail.capacity);
                $('#tabledetail').css({ 'top': dtop + 'px', 'left': dleft + 'px' }).fadeIn(500);
            }).mouseout(function () {
                $('#tabledetail').hide();
            });
        });
    })();
  
    var dtop;
    var dleft;
    var tabledetail;
    var showTableDetail = function (top, left, detail) {
        dtop = top;
        dleft = left;
        tabledetail = detail;
    };
</script>
<div id="tablestatuswidget" style="border:1px solid #777; max-width:830px; max-height:830px; height: @(floorplanheight)px; width: @(floorplanwidth)px; margin: 0px; position: relative; margin: auto; background: transparent url(@Url.Action("GetImage", "Images", new { id = Model.First().FloorPlanFileName})) center center no-repeat">
    @*<img alt="floorplan" src="@Url.Action("GetImage", "Images", new { id = Model.First().FloorPlanFileName})" style="position: absolute; top: 0px; left: 0px; "/>*@
    <div style="display: block; position: absolute; top: 0px; left: 0px;">
        @foreach (var table in Model)
        {
            var file = string.Empty;
            if (table.Status == RestaurantTable.RestaurentTableStatus.Booked) {
                file = Url.Content("~/Content/themes/base/images/red.png");
            }
            if (table.Status == RestaurantTable.RestaurentTableStatus.Occupied) {
                file = Url.Content("~/Content/themes/base/images/blue.png");
            }
            if (table.Status == RestaurantTable.RestaurentTableStatus.Vacant) {
                file = Url.Content("~/Content/themes/base/images/green.png");
            }
            <img id="@("table_status" + table.TableId)" class="table-booking-status" data-status="@table.Status" src="@file" alt="@table.Status" style="position: absolute; top: @(table.Position.Y)px; left: @(table.Position.X)px;" onclick="if (bookingIsEnabled) bookThisTable.call(this,@table.TableId);" onmouseover="showTableDetail(@(table.Position.Y),@(table.Position.X+30), {tableid : @(table.TableId), price : @(table.Price), status: '@(table.Status)', capacity : @((int)table.TableType)})"/>
        
        }
        <div id="tabledetail" class="ui-helper-hidden ui-corner-all" style="position:absolute;z-index:100; height: 70px;width:150px; background-color: #333; color:#eee; border:2px solid #fff; padding:20px">
            <div><label style="display: inline-block; min-width: 70px">Table Id</label> : <span id="tabledetail_table_id">Test details</span></div>
            <div><label style="display: inline-block; min-width: 70px">Price</label> : Rs.<span id="tabledetail_table_price">Test details</span>/-</div>
            <div><label style="display: inline-block; min-width: 70px">Status</label> : <span id="tabledetail_table_status">Test details</span></div>
            <div><label style="display: inline-block; min-width: 70px">Capicity</label> : <span id="tabledetail_table_capacity">Test details</span></div>
            <p></p>
        </div>  
    </div>
</div>
@* ReSharper restore UnknownCssClass *@