Solution/RestaurantBookingSystem/Controllers/TablesController.cs
using System;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantBookingSystem.Infrastructure.DataEntities;
using RestaurantBookingSystem.Infrastructure.Providers;
using RestaurantBookingSystem.Infrastructure.Repositories;
using RestaurantBookingSystem.Infrastructure;
using RestaurantBookingSystem.Helpers;
using RestaurantBookingSystem.Models;

namespace RestaurantBookingSystem.Controllers
{
    public class TablesController : Controller
    {
        private readonly RestaurantTableRepository Repository;
        private readonly int PageSize = AppConfigHelper.LargePageSize;

        // Initialize A custom cookie based temp data provider for the controller
        protected override ITempDataProvider CreateTempDataProvider()
        {
            return new CookieBasedTempDataProvider();
        }

        //
        // GET: /Tables/
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int? id, int? page)
        {
            var alltables = Repository.SelectAll();
            if (id.HasValue)
                alltables = alltables.Where(table => table.TableId == id);
            var paginatedlist = new PaginatedList<RestaurantTable>(alltables, page ?? 1, page.HasValue ? PageSize : alltables.Count());
            return View(paginatedlist);
        }

        //
        // GET: /Tables/CurrentStatus
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult CurrentStatus()
        {
            ViewBag.Title = ViewBag.Title ?? "Current Status";
            return
                StatusOn(DateTime.UtcNow.Floor((long) AppConfigHelper.BookingSlotMinutes,
                                            DateTimeHelper.DateTimePrecisionLevel.Minutes), null);
        }

        // GET: /Tables/StatusOn
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult StatusOn()
        {
            ViewBag.Title = ViewBag.Title ?? "Status On";
            return CurrentStatus();
        }

        //
        // POST: /Tables/StatusOn
        [HttpPost]
        public ActionResult StatusOn(DateTime fromdatetime, DateTime? todatetime)
        {
            fromdatetime = fromdatetime.ToUniversalTime();
            todatetime = todatetime != null ? todatetime.Value.ToUniversalTime() : fromdatetime.AddMinutes(AppConfigHelper.BookingSlotMinutes);
            // make sure we do not show status before shop opening time
            //fromdatetime = new DateTime(Math.Max(DateTime.UtcNow.TryMakingLocalToClient().Date.AddHours(7).Ticks, fromdatetime.TryMakingLocalToClient().Ticks), DateTimeKind.Unspecified).TryMakingUnivarsalFromClient();
            //todatetime = new DateTime(Math.Max(DateTime.UtcNow.TryMakingLocalToClient().Date.AddHours(7).AddMinutes(AppConfigHelper.BookingSlotMinutes).Ticks, (todatetime.Value.TryMakingLocalToClient()).Ticks), DateTimeKind.Unspecified).TryMakingUnivarsalFromClient();
            var result = Repository.SelectAll(fromdatetime, todatetime.Value);
            if (Request.IsAjaxRequest())
            {
                //If request is Ajax then send a JSON representation of the Dictionary, Also send the Date as a string so it can be easily parsed by client
                return
                    Json(
                        result
                        .ToDictionary(kvp => kvp.Key.ToISODateTimeString(), kvp => kvp.Value)
                        .ToLookup(kvp => new { kvp.Key, kvp.Value }));
            }
            return View("StatusOn",result);
        }

        //
        // GET: /Tables/Add
        [Authorize(Roles = "Admin")]
        public ActionResult Add()
        {
            return View(new RestaurantTableModel());
        } 

        //
        // POST: /Tables/Add

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Add(RestaurantTableModel model, HttpPostedFileBase floorplan)
        {
            try
            {
                //Explicitly Validate Model for floorplan image or previous image guid
                var floorplanfileguid = Guid.Empty;
                if (floorplan == null && !Guid.TryParse(model.FloorPlanFileName, out floorplanfileguid))
                    ModelState.AddModelError("addstatus", "One of the Given Floor Plans need to be selected");
                if (floorplan != null && (floorplan.ContentLength < 1 || (floorplan.ContentType != "image/jpeg" && floorplan.ContentType != "image/png")))
                    ModelState.AddModelError("addstatus", "A Floor Plan needs to have a valid Floor Plan Image, Only JPEG and PNG images are supported");
                if (ModelState.IsValid)
                {
                    // Attempt to add the offer
                    var restauranttable = new RestaurantTable
                                              {
                                                  TableType = model.TableType,
                                                  Alignment = model.Alignment,
                                                  Position = new Point(model.PositionX, model.PositionY),
                                                  Price = model.Price,
                                                  FloorPlanFileName = floorplanfileguid == Guid.Empty ? new ImagesController().PutImage(floorplan, null).ToString("n") : floorplanfileguid.ToString("n")
                                              };

                    var tableid = Repository.Add(restauranttable);
                    if (tableid > 0)
                    {
                        TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                        {
                            Message = String.Format("Table Id:{0}, with seating capacity of {1} was successfully Added", tableid, (int)model.TableType),
                            Result = true,
                            State = ActionResultNotification.MessageState.Information
                        };
                        return RedirectToAction("Index");
                    }
                }
                // If we got this far, something failed, redisplay form
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = ModelState.ContainsKey("addstatus") ? ModelState["addstatus"].Errors[0].ErrorMessage : "There was an Error in adding the new Table, please try again",
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
            catch (Exception e)
            {
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = e.Message,
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
        }

        //
        // POST: /Tables/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, int price)
        {
            if (Request.IsAjaxRequest())
                try
                {
                    var existingTable = Repository.Find(id);
                    if (existingTable == null) throw new Exception(String.Format("Sorry update cannot be done as Table with Id: {0} does not exist", id));
                    existingTable.Price = price;

                    //Push the changed details
                    if (Repository.Update(existingTable))
                    {
                        return Json(
                                    new ActionResultNotification
                                    {
                                        Message = String.Format("Details for Table Id:{0} was successfully Updated", existingTable.TableId),
                                        Result = true
                                    });

                    }
                    // If we got this far, something failed, redisplay form
                    return Json( 
                                new ActionResultNotification
                                {
                                    Message = "Cannot Update the details of the table with given details, please try again",
                                    Result = false
                                }); 
                }
                catch(Exception e)
                {
                    return
                        Json(
                            new ActionResultNotification
                            {
                                Result = false,
                                Message = e.Message
                            });
                }
            return RedirectToAction("Index");
        }

        //
        // POST: /Tables/Delete/5

        //Only Ajax Request is processed, a normal post request is redirected to Index action method
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            if (Request.IsAjaxRequest())
            {
                try
                {
                    var table = Repository.Find(id);
                    var result = false;
                    if (table != null)
                        result = Repository.Delete(id);
                    var message = result ? String.Format("The Table {0} with seating capicity of {1} was succcessfully deleted", table.TableId, (int)table.TableType) : String.Format("Failed to delete the Table, please try again");
                    return
                        Json(
                            new ActionResultNotification

Solution/RestaurantBookingSystem/Views/Tables/Add.cshtml
@using RestaurantBookingSystem.Infrastructure.DataEntities
@using RestaurantBookingSystem.Infrastructure.Repositories
@model RestaurantBookingSystem.Models.RestaurantTableModel
@{
    ViewBag.Title = "Add Table";
}
<h2>Add Table</h2>
@section head
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
@using (Html.BeginForm("Add", "Tables", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Enter Details for a new table</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.TableType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TableType)
            @Html.ValidationMessageFor(model => model.TableType)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Alignment)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Alignment)
            @Html.ValidationMessageFor(model => model.Alignment)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PositionX)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PositionX)
            @Html.ValidationMessageFor(model => model.PositionX)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PositionY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PositionY)
            @Html.ValidationMessageFor(model => model.PositionY)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FloorPlanFileName)
        </div>
        <div class="editor-field">
            @{
                var floorplan = new Dictionary<string, string> { { "---Select---", String.Empty } };
                var tables = new RestaurantTableRepository().SelectAll().GroupBy(table => table.FloorPlanFileName);
                if (tables.Count() > 0)
                {
                    // ReSharper disable ReturnValueOfPureMethodIsNotUsed
                    tables.Select((group, index) =>
                    {
                        floorplan.Add("Floor Plan " + (index+1), group.Key);
                        return true;
                    }).ToList();
                    // ReSharper restore ReturnValueOfPureMethodIsNotUsed
                }
                //floorplan = new Dictionary<string, string> { { "---Select---", String.Empty }, { "Floor Plan 1", Guid.NewGuid().ToString("n") }, { "Floor Plan 2", Guid.NewGuid().ToString("n") } };
            }
            @if (floorplan.Count() > 1)
            {
                @Html.DropDownList("FloorPlan", floorplan.Select((kvp) => new SelectListItem { Selected = false, Text = kvp.Key, Value = kvp.Value }));
            }
            else
            {
                <input type="file" id="FloorPlan" name="FloorPlan" />
            }
            <span class="ui-helper-hidden">@Html.EditorFor(model => model.FloorPlanFileName)</span>
            @Html.ValidationMessageFor(model => model.FloorPlanFileName)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $('#FloorPlanFileName').val($('#FloorPlan').val());
    if ($('#Price').val() === '0') $('#Price').val('');
    if ($('#PositionX').val() === '0') $('#PositionX').val('');
    if ($('#PositionY').val() === '0') $('#PositionY').val('');
    $('#FloorPlanFileName').disableSelection().css({ 'background-color': '#ddd' });
    $('#FloorPlan').change(function () {
        console.log($(this).val());
        $('#FloorPlanFileName').val($(this).val());
    });
</script>

Solution/RestaurantBookingSystem/Views/Tables/Index.cshtml
@using RestaurantBookingSystem.Infrastructure
@using RestaurantBookingSystem.Infrastructure.DataEntities
@using RestaurantBookingSystem.Infrastructure.Repositories
@model PaginatedList<RestaurantTable>
@* ReSharper disable UnknownCssClass *@
@{
    ViewBag.Title = "Index";
    var floorplan = new Dictionary<string, string>();
    var tables = new RestaurantTableRepository().SelectAll().GroupBy(table => table.FloorPlanFileName);
    if (tables.Count() > 0)
    {
        // ReSharper disable ReturnValueOfPureMethodIsNotUsed
        tables.Select((group, index) =>
        {
            floorplan.Add(group.Key, "Floor Plan " + (index + 1));
            return true;
        }).ToList();
        // ReSharper restore ReturnValueOfPureMethodIsNotUsed
    }
}
@section head{
    <script src="@Url.Content("~/Scripts/RestaurantBookingSystemScripts/RestaurantBookingSystemClientCore.js")"
        type="text/javascript"></script>
}
<h2>Tables List:</h2>
<hr />
<div>
    <table summary="Restaurant Tables">
        <thead>
            <tr>
                <th scope="col">
                    Id
                </th>
                <th scope="col">
                    TableType
                </th>
                <th scope="col">
                    Alignment
                </th>
                <th scope="col">
                    Position
                </th>
                <th scope="col">
                    Price
                </th>
                <th scope="col">
                    Floor Plan
                </th>
                <th scope="col">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="@("item_row" + item.TableId)">
                    <td>@item.TableId
                    </td>
                    <td>@item.TableType
                    </td>
                    <td>@item.Alignment
                    </td>
                    <td>@item.Position
                    </td>
                    <td>
                        Rs. <span id="@("item_price_span" + item.TableId)">@item.Price</span><input class="ui-helper-hidden" id="@("item_price_input" + item.TableId)" type="number" value="@item.Price"/>
                        /-
                    </td>
                    <td>@(floorplan[item.FloorPlanFileName])
                    </td>
                    <td class="table-td-action">
                        <a class="edit_row" 
                             onclick="editPrice('@Url.Action("Edit")', '@item.TableId')">Edit</a> <a class="delete_row"  onclick="deleteRow('@Url.Action("Delete")', '@item.TableId', '@((int)item.TableType)', '@item.Price')">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination-box">
        <strong>Showing Page @(Model.PageNumber)
            of @(Model.TotalPages > 0 ? Model.TotalPages : 1):</strong> <span class="pagination-box-button-set">
                @if (Model.HasPreviousPage)
                {
                    @Html.ActionLink("Previous", "Index", new { page = Model.PageNumber - 1 }, new { @class = "paginated-list-prev" })
                }
                @if (Model.HasNextPage)
                {
                    @Html.ActionLink("Next", "Index", new { page = Model.PageNumber + 1 }, new { @class = "paginated-list-next" })
                }
            </span>
    </div>
</div>
<div id="dialog-confirm" class="ui-helper-hidden" title="Delete Table?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Table with seating Capacity <span id="dialog-confirm-item-type"></span> Worth Rs.
        <span id="dialog-confirm-item-name"></span>/- will be permanently deleted.</p>
    <p style="margin: 0 0px 0px 22px;">
        Are you sure?</p>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.edit_row').button({
            icons: {
                primary: "ui-icon-pencil"
            },
            text: false
        });
        $('.delete_row').button({
            icons: {
                primary: "ui-icon-closethick"
            },
            text: false
        });
        $('.paginated-list-prev').button({
            label: 'Previous',
            icons: {
                primary: "ui-icon-seek-prev"
            }
        });
        $('.paginated-list-next').button({
            icons: {
                secondary: "ui-icon-seek-next"
            },
            label: 'Next'
        });
    });
    function editPrice(editUrl, tableId) {
        $('#item_price_span' + tableId).hide();
        //$('#item_price_input' + tableId).css('width', $('#item_price_span' + tableId).css('width'));
        $('.item_row' + tableId + ' .edit_row').button({
            icons: {
                primary: "ui-icon-circle-check"
            },
            text: false
        });
        $('#item_price_input' + tableId).keypress(function (e) {
            if (e.keyCode == 13) {
                var newval = parseInt($(this).val());
                if ($.isNaN(newval) || newval == 0)
                    showViewNotification(false, 'Invalid Value given for price, please correct it.');
                else {
                    $(this).val(newval);
                    $(this).disableSelection();
                    $.post(editUrl, { 'id': tableId, 'price': newval }, function (responsejson, status) {
                        if (status == 'success') {
                            if (responsejson.Result) {
                                $('#item_price_span' + tableId).text(newval).show();
                                $('.item_row' + tableId + ' .edit_row').button({
                                    icons: {
                                        primary: "ui-icon-pencil"
                                    },
                                    text: false
                                });
                                $('#item_price_input' + tableId).enableSelection(); 
                                $('#item_price_input' + tableId).hide();
                            }
                            showViewNotification(responsejson.Result, responsejson.Message);
                        }
                        else {
                            showViewNotification(false, 'There was some network related error, please try again');
                        }
                    }, 'json');
                }
            }
        });
        $('#item_price_input' + tableId).show();
    };
</script>
@* ReSharper restore UnknownCssClass *@

Solution/RestaurantBookingSystem/Views/Tables/StatusOn.cshtml
@using RestaurantBookingSystem.Infrastructure.DataEntities
@using RestaurantBookingSystem.Helpers
@model IDictionary<DateTime, IEnumerable<RestaurantTable>>
           
@section head{
    <script src="@Url.Content("~/Scripts/RestaurantBookingSystemScripts/BookingHelper.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RestaurantBookingSystemScripts/RestaurantBookingSystemClientCore.js")" type="text/javascript"></script>
}
@{
    ViewBag.Title = ViewBag.Title ?? "Status as on";
    if (Model.Count < 1)
    {
        return;
    }
    var modeldatetime = @Model.First().Key.TryMakingLocalToClient();
    var starttime = new DateTime(1, 1, 1, 7, 0, 0, 0); //7 AM
    var inittime = DateTime.MinValue ;
    var modeltime = (int)Math.Floor((new DateTime(1, 1, 1, modeldatetime.Hour, modeldatetime.Minute, 0, 0, 0) - inittime).TotalMilliseconds);
    var endtime = new DateTime(1, 1, 2, 0, 0, 0, 0); // late night 12 AM
    var breakfast = new DateTime(1, 1, 1, 7, 0, 0, 0); // 7: AM
    var lunch = new DateTime(1, 1, 1, 13, 0, 0, 0); // 1:00 PM
    var dinner = new DateTime(1, 1, 1, 20, 0, 0, 0); // 8:00 PM
    var timelist = new Dictionary<string, int>{{"--Select Time--", -1}};
    for (; starttime < endtime; starttime = starttime.AddMinutes(AppConfigHelper.BookingSlotMinutes))
    {
        if (starttime >= breakfast && starttime < breakfast.AddMinutes(AppConfigHelper.BookingSlotMinutes))
        {
            timelist.Add(starttime.ToString("h:mm tt") + " - Breakfast", (int)Math.Floor((starttime - inittime).TotalMilliseconds));
            continue;
        }
        if (starttime >= lunch && starttime < lunch.AddMinutes(AppConfigHelper.BookingSlotMinutes))
        {
            timelist.Add(starttime.ToString("h:mm tt") + " - Lunch", (int)Math.Floor((starttime - inittime).TotalMilliseconds));
            continue;
        }
        if (starttime >= dinner && starttime < dinner.AddMinutes(AppConfigHelper.BookingSlotMinutes))
        {
            timelist.Add(starttime.ToString("h:mm tt") + " - Dinner", (int)Math.Floor((starttime - inittime).TotalMilliseconds));
            continue;
        }
        timelist.Add(starttime.ToString("h:mm tt"), (int)Math.Floor((starttime - inittime).TotalMilliseconds));
    }
    var selecttimelist = timelist.Select(kvp => new SelectListItem {Text = kvp.Key, Value = kvp.Value.ToString(), Selected = kvp.Value == modeltime});
}
<h2>Status as on: <span id = "span_statusason">@Model.First().Key.ToString("dd MMM, h:mm tt")</span></h2>
<div class="h-seperator"></div>
<div style="margin:10px 0px;">
    <span class="editor-label">
    <span>Get Status for:</span>
    </span>
    <span class="editor-field">
        <input style="min-width: 17em;" id="fromdate" name="fromdate" type="date" value="@Model.First().Key.ToString("dddd, dd MMM yyyy")" />
        @Html.DropDownList("fromtime", selecttimelist)
        <button id="go">Go</button>
    </span>
</div>
<div id="div_table_status" class="ui-corner-all">
@Html.Partial("tablestatus", Model.First().Value)
</div>
<script type="text/javascript">
    var shortMonthString = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    $('button').button();
    $('#go').click(function () {
        var fromdate = new Date($('#fromdate').val());
        var fromtime = parseInt($('#fromtime').val());
        if (!isNaN(fromdate.getTime()) && fromtime > 1) {
            var fromdatetime = new Date(fromdate.getTime() + fromtime);
            var tablestatus = getTableStatusOn('@Url.Action("StatusOn", "Tables")', fromdatetime, 1, @(AppConfigHelper.BookingSlotMinutes) , function () {
                console.log(this.KeyValuePairs[0].Key);
                $(this.KeyValuePairs.firstOrDefault().Value.Items).each(function() {
                    setTableStatus(this);
                    $('#span_statusason').text(fromdatetime.getDate() + ' ' + shortMonthString[fromdatetime.getMonth()] + ', ' + fromdatetime.getHours() % 12 +':' + (fromdatetime.getMinutes() < 10 ? '0'+fromdatetime.getMinutes() : fromdatetime.getMinutes()) + ' ' + (fromdatetime.getHours() / 12 < 1 ? 'AM' : 'PM'));
                });
            });
        }
    });
    $("#fromdate").datepicker({
        minDate : '0D',
        maxDate : '+3M',
        dateFormat : "DD, d MM, yy",
        changeMonth : true
    });
</script>