Solution/RestaurantBookingSystem/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using RestaurantBookingSystem.Helpers;
using System.Web.Mvc;

namespace RestaurantBookingSystem.Controllers
{
    public class ImagesController : Controller
    {
        [OutputCache(Duration = 3600, VaryByHeader = "Etag")]
        public FileStreamResult GetImage(string id)
        {
            Guid guid;
            if (Guid.TryParse(id,out guid) && guid != Guid.Empty)
            {
                using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
                using (var cmd = new SqlCommand("[dbo].[GetBlob]", cn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;

                    try
                    {
                        cn.Open();
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.SequentialAccess))
                        {
                            if (rdr.HasRows && rdr.Read())
                            {
                                var result = new
                                                 {
                                                     ID = rdr.TryGetDataAsGuid(0),
                                                     MimeType = rdr.TryGetDataAsString(1),
                                                     ImageBlobStream = rdr.GetSqlBytes(2).Stream,
                                                     Sha1Hash = rdr.GetString(3)
                                                 };
                                if (Response != null)
                                    Response.Cache.SetETag(result.Sha1Hash);
                                return File(result.ImageBlobStream, result.MimeType);
                            }
                        }
                    }
                    catch (SqlException)
                    {
                        return null;
                    }
                }
            }
            //Set etag even for invalid image response so that they dont come back again asking for it
            Response.Cache.SetETag(CryptographyHelper.GetSHA1Hash(guid.ToString("n")));
            return null;
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Put)]
        [Authorize]
        public Guid PutImage(HttpPostedFileBase image, Guid? id)
        {
            var result = Guid.Empty;
            if (image == null || image.ContentLength < 1)
                return result;
            
            using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
            using (var cmd = new SqlCommand("[dbo].[AddBlob]", cn))
            {
                var guid = id ?? Guid.NewGuid();
                var buffer = image.InputStream.ReadToEnd();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;
                cmd.Parameters.Add("@MIMETYPE", SqlDbType.Char, 20).Value = image.ContentType;
                cmd.Parameters.Add("@BLOB", SqlDbType.VarBinary, image.ContentLength).Value = buffer;
                cmd.Parameters.Add("@SHA1HASH", SqlDbType.Char, 40).Value =
                    CryptographyHelper.GetSHA1Hash(buffer);

                try
                {
                    cn.Open();
                    return Guid.TryParse(cmd.ExecuteScalar().ToString(), out result) ? result : Guid.Empty;
                }
                catch (SqlException)
                {
                    return result;
                }
                
            }
        }

        [AcceptVerbs(HttpVerbs.Post | HttpVerbs.Delete)]
        [Authorize(Roles = "Admin, Employee")]
        [OutputCache(Duration = 3600, VaryByParam = "id")]
        public bool DeleteImage(string id)
        {
            var result = false;
            Guid guid;
            if (id == null || !Guid.TryParse(id, out guid) || guid == Guid.Empty)
                return false;

            using (var cn = new SqlConnection(DatabaseConnection.ConnectionStringToDb))
            using (var cmd = new SqlCommand("[dbo].[DeleteBlob]", cn))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@UID", SqlDbType.UniqueIdentifier).Value = guid;

                try
                {
                    cn.Open();
                    return result = cmd.ExecuteNonQuery() == 1;
                }
                catch (SqlException)
                {
                    return result;
                }
            }
        }
    }
}

Solution/RestaurantBookingSystem/Controllers/OffersController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantBookingSystem.Helpers;
using RestaurantBookingSystem.Infrastructure;
using RestaurantBookingSystem.Infrastructure.DataEntities;
using RestaurantBookingSystem.Infrastructure.Providers;
using RestaurantBookingSystem.Infrastructure.Repositories;
using RestaurantBookingSystem.Models;

namespace RestaurantBookingSystem.Controllers
{
    [Authorize(Roles = "admin")]
    public class OffersController : Controller
    {
        private readonly OfferBaseRepository Repository;
        private readonly int PageSize = AppConfigHelper.MediumPageSize;

        // Initialize A custom cookie based temp data provider for the controller
        protected override ITempDataProvider CreateTempDataProvider()
        {
            return new CookieBasedTempDataProvider();
        }

        //
        // GET: /Offers/

        public ActionResult Index(int? id, int? page)
        {
            var alloffers = Repository.SelectAll();
            if (id.HasValue && id > 1)
                alloffers = alloffers.Where(offer => offer.OfferId == id);
            var paginatedlist = new PaginatedList<OfferBase>(alloffers, page ?? 1, page.HasValue ? PageSize : alloffers.Count());
            return View(paginatedlist);
        }

        //
        // GET: /Offers/Add
        [OutputCache(Duration = 3600)]
        public ActionResult Add()
        {
            return View(new AddOfferModel{ Type = (OfferBase.OfferType)(-1), PublishedBy = (AddOfferModel.PublishedVia)(-1)});
        } 

        //
        // POST: /Offers/Add

        [HttpPost]
        public ActionResult Add(AddOfferModel model, HttpPostedFileBase offerimage)
        {
            try
            {
                //Explicitly Validate Model for OfferType, PublishVia and offerimage
                if ((model.Type != OfferBase.OfferType.DiscountAmount 
                    && model.Type != OfferBase.OfferType.DiscountPercent 
                    && model.Type != OfferBase.OfferType.FreeServing) 
                    || 
                    (model.PublishedBy != AddOfferModel.PublishedVia.Advertisement 
                    && model.PublishedBy != AddOfferModel.PublishedVia.Code))
                    ModelState.AddModelError("addstatus", "An Offer needs to be one of the Offer Types and should have one of the Publish Medium");
                if (model.PublishedBy == AddOfferModel.PublishedVia.Advertisement 
                    && (offerimage == null || offerimage.ContentLength < 1
                    || offerimage.ContentType != "image/jpeg" && offerimage.ContentType != "image/png"))
                    ModelState.AddModelError("addstatus", "An Offer with Advertisement needs to have a valid Advertisement Image, Only JPEG and PNG images are supported");
                if (model.PublishedBy == AddOfferModel.PublishedVia.Code
                    && (model.CouponCode == null || model.CouponCode.Trim().Length < 1))
                    ModelState.AddModelError("addstatus", "An Offer with Code needs to have a valid Coupon Code");
                if (ModelState.IsValid)
                {
                    // Attempt to add the offer
                    var restaurantoffer = 
                        model.PublishedBy == AddOfferModel.PublishedVia.Advertisement
                        ? new SeasonalOffer
                                {
                                    Type = model.Type,
                                    Description = model.Description,
                                    Title = model.Title,
                                    ValidFrom = model.ValidFrom,
                                    ValidTill = model.ValidTill,
                                    Value = model.Value,
                                    PictureFileName =
                                        new ImagesController().PutImage(offerimage, null).
                                        ToString("n")
                                }
                        : new Coupon(model.CouponCode)
                                {
                                    Type = model.Type,
                                    Description = model.Description,
                                    Title = model.Title,
                                    ValidFrom = model.ValidFrom,
                                    ValidTill = model.ValidTill,
                                    Value = model.Value
                                } as OfferBase;

                    var offerid = Repository.Add(restaurantoffer);
                    if (offerid > 0)
                    {
                        TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                        {
                            Message = String.Format("Offer Id:{0}, {1} was successfully Added as a new {2}", offerid, model.Title, model.PublishedBy == AddOfferModel.PublishedVia.Code ? "Coupon" : "Seasonal Offer"),
                            Result = true,
                            State = ActionResultNotification.MessageState.Information
                        };
                        return RedirectToAction("Index");
                    }
                }
                // If we got this far, something failed, redisplay form
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = ModelState.ContainsKey("addstatus") ? ModelState["addstatus"].Errors[0].ErrorMessage : "There was an Error in adding the new Offer, please try again",
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
            catch (Exception e)
            {
                TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                {
                    Message = e.Message,
                    Result = false,
                    State = ActionResultNotification.MessageState.Error
                };
                return View(model);
            }
        }
        
        //
        // GET: /Offers/Edit/5
 
        public ActionResult Edit(int id)
        {
            var offer = Repository.Find(id);

            if (offer != null)
            {
                if (offer is SeasonalOffer) ViewBag.PictureFileName = (offer as SeasonalOffer).PictureFileName;
                return View(new UpdateOfferModel(offer));
            }
            TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
            {
                Message = String.Format("No such offer Exists !"),
                Result = false,
                State = ActionResultNotification.MessageState.Error
            };
            return RedirectToAction("Index");
        }

        //
        // POST: /Offers/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, UpdateOfferModel model, HttpPostedFileBase offerimage)
        {
            try
            {
                // Get previous details
                var existingoffer = Repository.Find(id);
                if (existingoffer == null) throw new InvalidOperationException("Sorry the update cannot be done as no such offer exist");

                if (existingoffer is SeasonalOffer && model.PublishedBy == UpdateOfferModel.PublishedVia.Advertisement
                    && offerimage != null && (offerimage.ContentLength < 1
                    || (offerimage.ContentType != "image/jpeg" && offerimage.ContentType != "image/png")))
                {
                    ModelState.AddModelError("updatestatus",
                                             "An Seasonal Offer Advertisement needs to have a valid Advertisement Image, Only JPEG and PNG images are supported");
                    ViewBag.PictureFileName = (existingoffer as SeasonalOffer).PictureFileName;
                }

                if (ModelState.IsValid)
                {

                    // Attempt to Update the offer
                    if (existingoffer is SeasonalOffer && offerimage != null && offerimage.ContentLength > 0)
                    {
                        var previd = (existingoffer as SeasonalOffer).PictureFileName;
                        var imagecontroller = new ImagesController();
                        (existingoffer as SeasonalOffer).PictureFileName =
                            imagecontroller.PutImage(offerimage, null).ToString("n");
                        // if both image ids are not same then delete the prev id.
                        if (!String.Equals(previd, (existingoffer as SeasonalOffer).PictureFileName)) imagecontroller.DeleteImage(previd);
                    }

                    existingoffer.Description = model.Description;
                    existingoffer.Title = model.Title;
                    existingoffer.ValidTill = model.ValidTill;

                    //And push the changed details
                    if (Repository.Update(existingoffer))
                    {
                        TempData[TempDataStringResuorce.ActionResultNotification] = new ActionResultNotification
                            {
                                Message = String.Format("Details for {0} was successfully Updated", existingoffer.GetType().Name),
                                Result = true,
                                State = ActionResultNotification.MessageState.Information
                            };
                        return RedirectToAction("Index");
                    }
                }
                // If we got this far, something failed, redisplay form

Solution/RestaurantBookingSystem/Views/Offers/Add.cshtml
@using RestaurantBookingSystem.Infrastructure.Repositories
@model RestaurantBookingSystem.Models.AddOfferModel
@{
    ViewBag.Title = "New Offer";
}
<h2>
    New Offer</h2>
@section head
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
<div class="h-seperator">
</div>
@using (Html.BeginForm("Add", "Offers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Details for New Offer</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Type)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Value)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Value)
            @Html.ValidationMessageFor(model => model.Value)
            @Html.DropDownList("MenuItems", new RestaurantMenuItemRepository()
                .SelectAll()
                .Select(menuitem =>
                    new SelectListItem { Selected = false, Text = menuitem.Name, Value = menuitem.ItemId.ToString() })
             , new { @class = "ui-helper-hidden" })
            <input type="hidden" id="OfferValueHidden" />
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ValidFrom)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValidFrom)
            @Html.ValidationMessageFor(model => model.ValidFrom)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ValidTill)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValidTill)
            @Html.ValidationMessageFor(model => model.ValidTill)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PublishedBy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PublishedBy)
            @Html.ValidationMessageFor(model => model.PublishedBy)
        </div>
        <div id="offerpublishimage" class="ui-helper-hidden">
            <div class="editor-label">
                <label for="OfferImage">
                    Image for Advertisement</label>
            </div>
            <div class="editor-field">
                <input type="file" id="OfferImage" name="OfferImage" />
            </div>
            <input type="hidden" id="OfferImageHidden" />
        </div>
        <div id="offerpublishcode" class="ui-helper-hidden">
            <div class="editor-label">
                @Html.LabelFor(model => model.CouponCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.CouponCode)
                @Html.ValidationMessageFor(model => model.CouponCode)
            </div>
            <input type="hidden" id="CouponCodeHidden" />
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript" language="javascript">
    //A quick fix for default value of 0 in Offer Value Field
    $('input[type="text"][name="Value"]').val("");

    $('input[type="radio"][name="PublishedBy"]').change(function () {
        if ($(this).val() === 'Code') {
            $('#offerpublishimage').hide();
            $('#offerpublishcode').show();
            if ($('#CouponCodeHidden').val() != '') { $('#CouponCode').val($('#CouponCodeHidden').val()); }
            $('#OfferImage').val('');
        }
        if ($(this).val() === 'Advertisement') {
            $('#offerpublishcode').hide();
            $('#offerpublishimage').show();
            $('#CouponCodeHidden').val($('#CouponCode').val());
            $('#CouponCode').val('');
        }
    });

    var valueIsDirty = false;
    $('input[type="radio"][name="Type"]').change(function () {
        if ($(this).val() === 'FreeServing') {
            $('#Value').disableSelection().css('background-color', '#ddd');
            $('#OfferValueHidden').val($('#Value').val());
            $('#Value').val('');
            $('#MenuItems').show();
            valueIsDirty = true;
        }
        else {
            if (valueIsDirty) {
                $('#Value').val($('#OfferValueHidden').val());
                $('#MenuItems').hide();
                $('#Value').enableSelection().css('background-color', '#fff');
            }
        }
    });
    $('select[name="MenuItems"]').change(function () {
        if ($(this).hasClass('.ui-helper-hidden'))
            return;
        else {
            $('#Value').val($(this).val());
        }
    });
</script>

Solution/RestaurantBookingSystem/Views/Offers/Edit.cshtml
@using RestaurantBookingSystem.Models
@model UpdateOfferModel
@{
    ViewBag.Title = "Update Offer";
}
<h2>Update Offer</h2>
@section head
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
<div class="h-seperator">
</div>
@using (Html.BeginForm("Edit", "Offers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Enter Updated Details for the Offer</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ValidTill)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValidTill)
            @Html.ValidationMessageFor(model => model.ValidTill)
        </div>
        @if (Model.PublishedBy == UpdateOfferModel.PublishedVia.Advertisement)
        {
            <div class="editor-label">
                <label for="OfferImage">
                    Image for Advertisement</label>
            </div>
            <div style="margin: 0px; padding: 0px;">
                <div id="offer_previous_image"  class="ui-corner-all" style="margin:6px 8px; width:auto; height:300px;background: #fff url(@Url.Action("GetImage", "Images", new { id = ViewBag.PictureFileName })) 50% 50% no-repeat"/>
            </div>
            <div class="editor-field">
                <input type="file" id="OfferImage" name="OfferImage" />
            </div>
        }
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Solution/RestaurantBookingSystem/Views/Offers/Index.cshtml
@using RestaurantBookingSystem.Infrastructure
@using RestaurantBookingSystem.Infrastructure.DataEntities
@using RestaurantBookingSystem.Models
@model PaginatedList<OfferBase>

@{
    ViewBag.Title = "Offers List";
 }
 @section head{
        <script src="@Url.Content("~/Scripts/RestaurantBookingSystemScripts/RestaurantBookingSystemClientCore.js")"
        type="text/javascript"></script>
 }
<h2>Offers</h2>
<div class="h-seperator"></div>
<div>
    <table summary="Restaurant OFfers">
        <thead>
            <tr>
                <th scope="col">
                    Offer Id
                </th>
                <th scope="col">
                    Title
                </th>
                <th scope="col">
                    Type
                </th>
                <th scope="col">
                    Value
                </th>
                <th scope="col">
                    Valid From
                </th>
                <th scope="col">
                    Valid Till
                </th>
                <th scope="col">
                    Description
                </th>
                <th scope="col">
                    Offer Detail
                </th>
                <th scope="col">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="@("item_row" + item.OfferId.ToString())">
                    <td>@item.OfferId
                    </td>
                    <td>@item.Title
                    </td>
                    <td>@item.Type
                    </td>
                    <td>@item.Value
                    </td>
                    <td>@item.ValidFrom.ToLongDateString()
                    </td>
                    <td>@item.ValidTill.ToLongDateString()
                    </td>
                    <td>@item.Description
                    </td>
                    <td>
                        @if(item is Coupon)
                        {
                            <text>Coupon Code: @((item as Coupon).Code)</text>
                        }
                        else
                        {
                            <button id="@("offerdetail" + item.GetHashCode())" onclick="toggleoffer('@("seasonaloffer" + item.GetHashCode())', '@("offerdetail" + item.GetHashCode())')">Show Offer Image</button>
                        }
                    </td>
                    <td class="table-td-action">
                        <a class="edit_row"
                             href="@Url.Action("Edit", new { id = item.OfferId })">Edit</a> <a 
                             class="delete_row" onclick="deleteRow('@Url.Action("Delete")', '@item.OfferId', '@item.GetType().Name', '@item.Title')">Delete</a>
                    </td>
                </tr>
                if (!(item is SeasonalOffer)){continue;}
                <tr class="@("item_row" + item.OfferId.ToString())">
                    <td colspan="9" style="padding: 0px; margin: 0px;">
                        <div  id="@("seasonaloffer" + item.GetHashCode())" class="ui-helper-hidden ui-corner-all" style="margin:6px 8px; width:auto; height:300px;background: #fff url(@Url.Action("GetImage","Images", new { id = (item as SeasonalOffer).PictureFileName})) 50% 50% no-repeat"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination-box">
        <strong>Showing Page @(Model.PageNumber)
            of @(Model.TotalPages > 0 ? Model.TotalPages : 1):</strong>
        <span class="pagination-box-button-set">
        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("Previous", "Index", new { page = Model.PageNumber - 1 }, new { @class = "paginated-list-prev" })
        }
        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Next", "Index", new { page = Model.PageNumber + 1 }, new { @class = "paginated-list-next" })
        }
        </span>
    </div>
</div>
<div id="dialog-confirm" class="ui-helper-hidden" title="Delete Offer?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        <span id="dialog-confirm-item-type"></span> for "<span id="dialog-confirm-item-name">
        </span>" will be permanently deleted.</p>
    <p style="margin: 0 0px 0px 22px;">
        Are you sure?</p>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.edit_row').button({
            icons: {
                primary: "ui-icon-pencil"
            },
            text: false
        });
        $('.delete_row').button({
            icons: {
                primary: "ui-icon-closethick"
            },
            text: false
        });
        $('.paginated-list-prev').button({
            label: 'Previous',
            icons: {
                primary: "ui-icon-seek-prev"
            }
        });
        $('.paginated-list-next').button({
            icons: {
                secondary: "ui-icon-seek-next"
            },
            label: 'Next'
        });
    });
    
    function toggleoffer(offerelement, showhidebutton) {
        $('#' + offerelement).slideToggle(500);
        if ($('#' + showhidebutton).html() === "Show Offer Image")
            $('#' + showhidebutton).html("Hide Offer Image");
        else
            $('#' + showhidebutton).html("Show Offer Image");
    }
</script>